import { useCallback, useEffect, useMemo, useState } from 'react';
import { Modal } from '@components/feedback';
import { KVGrid } from '@components/data';
import { Button, Badge } from '@components/ui';
import Icon from '@icons';
import { fmt } from '@utils';
import { artifactThumb } from '@components/specialized/Gallery/Gallery';
import type { GalleryItem } from '@components/specialized/Gallery/Gallery.types';
import type { ArtifactViewerModalProps } from './ArtifactViewerModal.types';

export default function ArtifactViewerModal({ open, onClose, items = [], initialIndex = 0, onDelete, onDownload }: ArtifactViewerModalProps) {
  const [idx, setIdx] = useState(initialIndex); const safeIdx = Math.min(Math.max(0, idx), Math.max(0, items.length - 1)); const current = items[safeIdx] || null; const hasItems = items.length > 0;
  useEffect(() => { if (!open) return; setIdx(Math.min(Math.max(0, initialIndex), Math.max(0, items.length - 1))); }, [open, initialIndex, items]);
  const thumbSvg = useMemo(() => current ? artifactThumb(current) : '', [current]);
  const goPrev = useCallback(() => { if (hasItems) setIdx(value => (value - 1 + items.length) % items.length); }, [hasItems, items.length]); const goNext = useCallback(() => { if (hasItems) setIdx(value => (value + 1) % items.length); }, [hasItems, items.length]);
  useEffect(() => { if (!open) return undefined; const onKey = (event: KeyboardEvent) => { if (event.key === 'ArrowLeft') goPrev(); else if (event.key === 'ArrowRight') goNext(); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [open, goPrev, goNext]);
  const approxBytes = useMemo(() => { let value = 0; for (const character of (current?.id || 'art') + (current?.time || '')) value = (value * 31 + character.charCodeAt(0)) >>> 0; return 180000 + ((value % 1500) * 1000); }, [current]);
  return <Modal open={open} onClose={onClose} size="xl" title={current ? `Visionneuse · ${current.title || current.id || 'Artefact'}` : 'Visionneuse'} hideFooter footer={hasItems ? <><Button variant="quiet" onClick={onDelete ? () => onDelete(current as GalleryItem, safeIdx) : undefined} icon={<Icon name="alert" size={14} />}>Supprimer</Button><div style={{ marginRight: 'auto', fontFamily: 'var(--mono)', fontSize: 12, color: 'var(--text-3)', padding: '0 6px', alignSelf: 'center' }}>{safeIdx + 1} / {items.length}</div><Button variant="default" onClick={goPrev} icon={<Icon name="chev" size={12} />} iconRight={false}>Précédent</Button><Button variant="default" onClick={goNext} icon={<Icon name="chev" size={12} />}>Suivant</Button><Button variant="primary" onClick={onDownload ? () => onDownload(current as GalleryItem, safeIdx) : undefined} icon={<Icon name="inbox" size={14} />}>Télécharger</Button></> : undefined}>
    {!hasItems ? <div style={{ textAlign: 'center', padding: 40, color: 'var(--text-3)', fontSize: 13 }}>Aucun artefact à afficher.</div> : <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 2fr) minmax(220px, 1fr)', gap: 16 }}><div style={{ display: 'flex', flexDirection: 'column', gap: 10, minWidth: 0 }}><div style={{ position: 'relative', aspectRatio: '4 / 3', borderRadius: 12, overflow: 'hidden', background: 'var(--bg-3)', border: '1px solid var(--line-1)' }} dangerouslySetInnerHTML={{ __html: thumbSvg }} /><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 10, flexWrap: 'wrap' }}><Badge variant="brand">{current?.asset || '—'}</Badge><div style={{ fontFamily: 'var(--mono)', fontSize: 11.5, color: 'var(--text-3)' }}>{current?.time || ''}</div></div></div><div style={{ display: 'flex', flexDirection: 'column', gap: 12, minWidth: 0 }}><div><div style={{ fontSize: 10.5, color: 'var(--text-3)', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 2 }}>Titre</div><div style={{ fontSize: 14, fontWeight: 700 }}>{current?.title || `Artefact #${String(current?.id ?? safeIdx)}`}</div>{current?.subtitle && <div style={{ fontSize: 12.5, color: 'var(--text-2)', marginTop: 2 }}>{current.subtitle}</div>}</div><KVGrid pairs={[['ID artefact', current?.id || `g${safeIdx}`], ['Source', current?.asset || '—'], ['Heure capture', current?.time || '—'], ['Coordonnées', current?.lat != null && current?.lng != null ? `${current.lat.toFixed(4)}°, ${current.lng.toFixed(4)}°` : '—'], ['Poids estimé', fmt(approxBytes)], ['Type', 'Image · JPEG simulé']]} /><div style={{ padding: 10, borderRadius: 8, background: 'var(--bg-3)', border: '1px solid var(--line-1)', fontSize: 11.5, color: 'var(--text-3)', lineHeight: 1.45 }}><div style={{ fontWeight: 700, marginBottom: 3, color: 'var(--text-2)' }}><Icon name="info" size={12} style={{ marginRight: 4 }} />À propos</div>Vignette générée côté console par <code style={{ fontFamily: 'var(--mono)' }}>artifactThumb()</code>. Le fichier original reste stocké sur le serveur et est récupérable via <code style={{ fontFamily: 'var(--mono)' }}>GET /artifacts/{'{id}'}/content</code>.</div></div></div>}
  </Modal>;
}
