import { useState } from 'react';
import { Button, Badge } from '@components/ui';
import { Panel, HeroKPI, MetricsGrid } from '@components/data';
import { useToast } from '@components/feedback';
import Icon from '@icons';
import { Breakdown, TimelineDensity, RSSIBars, FrequencyBands, ActivityStream, AssetListRow, LiveTag, ConnectionIndicator, BandCards } from '@components/specialized';
import { SAMPLE_BAND_CELLS, SAMPLE_STREAM, SAMPLE_ASSETS, SAMPLE_TIMELINE } from '@/data/sampleData';

export default function DashboardView({ onOpenNewMission }: { onOpenNewMission?: () => void }) {
  const [paused, setPaused] = useState(false);
  const toast = useToast();
  return <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
    <div style={{ display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap', justifyContent: 'space-between' }}><div><div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 4 }}><h1 style={{ fontSize: 22, fontWeight: 700, margin: 0 }}>Tableau de bord opérationnel</h1><LiveTag /></div><div style={{ color: 'var(--text-3)', fontSize: 13 }}>Douala · Cameroun · Mise à jour il y a 4 s</div></div><div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><ConnectionIndicator state="up" /><Button variant="default" icon={<Icon name="obs" size={14} />}>Rafraîchir</Button><Button variant="primary" icon={<Icon name="mission" size={14} />} onClick={onOpenNewMission}>Nouvelle mission</Button></div></div>
    <BandCards cells={SAMPLE_BAND_CELLS} />
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(12, 1fr)', gap: 16 }}>
      <div style={{ gridColumn: 'span 8' }}><Breakdown title="Répartition Wi-Fi" lead={1595} unit="uniques" sub="24 dernières heures · RSSI moyen : -71 dBm" parts={[{ name: "Points d'accès", value: 214, colorVar: '--dblue' }, { name: 'Stations', value: 1122, colorVar: '--dblue-soft' }, { name: 'Inconnus', value: 259, colorVar: '--n400' }]} facts={[{ label: 'SSIDs uniques', value: 186, help: 'Réseaux annonçant leur nom' }, { label: 'Réseaux masqués', value: 23, tone: 'warn', help: 'SSIDs non diffusés' }, { label: 'RSSI moyen', value: '-71 dBm' }, { label: 'Couverture 2.4 GHz', value: '100 %' }]} /></div>
      <div style={{ gridColumn: 'span 4' }}><Breakdown title="Répartition Bluetooth" lead={2450} unit="uniques" sub="Périphériques détectés · 1504 adresses aléatoires" parts={[{ name: 'Nommé', value: 612, colorVar: '--dblue' }, { name: 'Connectable', value: 341, colorVar: '--ok' }, { name: 'LE only', value: 1904, colorVar: '--dblue-soft' }]} facts={[{ label: 'Publiques', value: 733 }, { label: 'Aléatoires', value: 1502 }, { label: 'BR/EDR', value: 546 }, { label: 'Non classés', value: 215, tone: 'warn' }]} /></div>
      <div style={{ gridColumn: 'span 6' }}><Panel title="Distribution RSSI" icon={<Icon name="obs" />}><RSSIBars distribution={{ near: 118, mid: 642, far: 1104, weak: 1181 }} /></Panel></div>
      <div style={{ gridColumn: 'span 6' }}><Panel title="Bandes de fréquences" icon={<Icon name="asset" />}><FrequencyBands bands={{ b24: 142, b5: 66, b6: 6, other: 0 }} /></Panel></div>
      <div style={{ gridColumn: 'span 6' }}><Panel title="Flux d'activité" icon={<Icon name="inbox" />} right={<Badge variant="brand" dot>{SAMPLE_STREAM.length + 148}</Badge>}><ActivityStream items={SAMPLE_STREAM} maxHeight={280} paused={paused} onPauseToggle={() => setPaused(value => !value)} onViewAll={() => toast.show('Ouvre le journal complet', { tone: 'info' })} onItemClick={item => toast.show(`Événement sélectionné : ${item.time}`, { tone: 'info' })} /></Panel></div>
      <div style={{ gridColumn: 'span 6' }}><Panel title="Flotte — état actuel" icon={<Icon name="asset" />} right={<Badge variant="ok" dot>5 actifs</Badge>}><div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>{SAMPLE_ASSETS.map(asset => <AssetListRow key={asset.id} asset={asset} color={asset.asset_type === 'drone' ? 'var(--cls-drone)' : 'var(--cls-ground)'} onClick={selected => toast.show(`Ouverture : ${selected.name}`, { tone: 'ok' })} />)}</div></Panel></div>
      <div style={{ gridColumn: 'span 12' }}><Panel title="Timeline opérationnel · 72 dernières heures" icon={<Icon name="obs" />}><div><div style={{ display: 'flex', alignItems: 'center', gap: 16, marginBottom: 12, flexWrap: 'wrap' }}><h3 style={{ fontSize: 14, fontWeight: 700, margin: 0 }}>Densité par type</h3><div style={{ display: 'flex', gap: 14, fontSize: 11, color: 'var(--text-3)' }}>{[['--dblue', 'Observations'], ['--dblue-soft', 'Zones'], ['--brand-soft', 'Captures'], ['--danger-soft', 'Alertes']].map(([color, label]) => <span key={label} style={{ display: 'flex', alignItems: 'center', gap: 6 }}><span style={{ width: 8, height: 8, background: `var(${color})`, borderRadius: 2 }} />{label}</span>)}</div><div style={{ marginLeft: 'auto', fontFamily: 'var(--mono)', fontSize: 12, color: 'var(--text-3)' }}>256 événements</div></div><TimelineDensity columns={72} data={SAMPLE_TIMELINE} cursorIndex={52} highlightNow /></div></Panel></div>
      <div style={{ gridColumn: 'span 12' }}><Panel title="KPI Héroïques" icon={<Icon name="ops" />}><HeroKPI items={[{ label: 'Appareils déclarés', value: 5, unit: 'sur 6', tone: 'ok', sub: 'Triangle3 désactivé' }, { label: 'Alertes critiques (24h)', value: 0, tone: 'ok', sub: 'Aucun incident sérieux' }, { label: 'Batterie min. flotte', value: 9, unit: '%', tone: 'danger', sub: 'Triangle2 à recharger' }]} /><div style={{ marginTop: 14 }}><MetricsGrid metrics={[{ label: 'Images capturées', value: 95 }, { label: 'Rapports totaux', value: '3 124' }, { label: 'Zones couvertes', value: 10 }, { label: 'Missions actives', value: 1 }, { label: 'Historique', value: '108 j' }, { label: 'Replay dispo.', value: '3 h' }, { label: 'Tx horaires', value: 47 }, { label: 'Latence', value: '1,3 s' }]} /></div></Panel></div>
    </div>
  </div>;
}
