import { Badge } from '@components/ui';
import { Panel, KVGrid } from '@components/data';
import { useToast } from '@components/feedback';
import Icon from '@icons';
import { VideoFrame, VideoPlayer, MapPanel } from '@components/specialized';
import { SAMPLE_ASSETS, SAMPLE_STREAM, SAMPLE_TRACK } from '@/data/sampleData';

export default function MapView() {
  const toast = useToast();
  return <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
    <Panel title="Lecteur de trajet · skydroid1" icon={<Icon name="asset" />} right={<Badge variant="ok" dot>Relecture</Badge>} collapsible><VideoPlayer track={SAMPLE_TRACK} assetName="skydroid1" autoPlay /></Panel>
    <Panel title="Console vidéo · image par image" icon={<Icon name="image" />} collapsible><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 14 }}>{[0, 10, 20, 30].map(index => { const frame = SAMPLE_TRACK[index]; return <div key={index}><VideoFrame {...frame} /><KVGrid pairs={[['Temps', `T+${Math.round(frame.t)}s`], ['Altitude', `${frame.alt} m`], ['Vitesse', `${frame.speed.toFixed(1)} m/s`], ['Batterie', `${frame.batt} %`]]} style={{ marginTop: 8 }} /></div>; })}</div></Panel>
    <Panel title="Panneau latéral carte (simulé)" icon={<Icon name="panel" />}><div style={{ height: 440, position: 'relative', background: 'var(--bg-2)', border: '1px solid var(--line-1)', borderRadius: 10, overflow: 'hidden' }}><div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-3)', fontSize: 12, background: 'linear-gradient(var(--line-1) 1px, transparent 1px) 0 0 / 40px 40px, linear-gradient(90deg, var(--line-1) 1px, transparent 1px) 0 0 / 40px 40px, var(--bg-3)' }}><div style={{ textAlign: 'center', padding: 20 }}><Icon name="map" size={36} style={{ opacity: 0.3 }} /><div style={{ marginTop: 8 }}>Carte Google Maps — chargement différé</div><div style={{ fontSize: 11, opacity: 0.6, marginTop: 4 }}>Douala, CM · 4.0511, 9.7679</div></div></div><MapPanel tabs={[{ label: 'Appareils', count: SAMPLE_ASSETS.length, type: 'list', items: SAMPLE_ASSETS.map(asset => ({ id: asset.id, title: asset.name, subtitle: `${asset.battery}% · ${asset.last}`, color: asset.asset_type === 'drone' ? 'var(--cls-drone)' : 'var(--cls-ground)', right: <Badge variant="ok">OK</Badge> })), onItemClick: item => toast.show(`Sélection : ${item.title}`, { tone: 'info' }) }, { label: 'Zones', count: 4, type: 'list', items: [{ id: 'z1', title: 'Périmètre nord', subtitle: 'Opération · 5 sommets', color: 'var(--dblue)', right: <Badge variant="brand">M1</Badge> }, { id: 'z2', title: 'Couloir aérien', subtitle: 'Exclusion · 4 sommets', color: 'var(--danger)', right: <Badge variant="danger">EXCL</Badge> }] }, { label: 'Événements', count: 12, type: 'feed', items: SAMPLE_STREAM.map(stream => ({ time: stream.time, text: stream.html })) }]} /><div style={{ position: 'absolute', bottom: 12, left: 12, zIndex: 4, background: 'var(--bg-1)', border: '1px solid var(--line-1)', borderRadius: 10, padding: 10, minWidth: 220 }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 12, fontWeight: 700, marginBottom: 8 }}><Icon name="map" size={14} /> Légende</div>{[['var(--cls-drone)', 'Drone (vol)'], ['var(--cls-ground)', 'Station sol'], ['var(--dblue)', 'Point Wi-Fi'], ['var(--brand)', 'Émetteur BT'], ['var(--danger)', 'Zone exclusion']].map(([color, label], index) => <div key={index} style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 11.5, padding: '3px 0' }}><span style={{ width: 14, height: 14, borderRadius: 999, border: `2px solid ${color}`, background: `${color}33` }} /><span style={{ color: 'var(--text-2)' }}>{label}</span></div>)}</div></div></Panel>
  </div>;
}
