import { useEffect, useMemo, useState } from 'react';
import { Field, SegmentedControl, Alert } from '@components/ui';
import { Modal } from '@components/feedback';
import { TokenBox } from '@components/specialized';
import { KVGrid } from '@components/data';
import Icon from '@icons';
import type { IssueTokenModalProps, IssuedToken } from './IssueTokenModal.types';

const DEFAULT_SCOPES = [{ id: 'asset.report', label: 'Rapports télém.', default: true }, { id: 'obs.ingest', label: 'Ingestion obs.', default: true }, { id: 'media.upload', label: 'Upload média', default: false }, { id: 'cmd.issue', label: 'Commandes', default: false }];
export default function IssueTokenModal({ open, onClose, asset, onCreate }: IssueTokenModalProps) {
  const [step, setStep] = useState(0); const [validity, setValidity] = useState(0); const [scopeBits, setScopeBits] = useState(() => DEFAULT_SCOPES.map(scope => scope.default)); const [issuedToken, setIssuedToken] = useState<IssuedToken | null>(null); const [touched, setTouched] = useState(false);
  useEffect(() => { if (!open) { setStep(0); setValidity(0); setScopeBits(DEFAULT_SCOPES.map(scope => scope.default)); setIssuedToken(null); setTouched(false); } }, [open]);
  const selectedScopes = DEFAULT_SCOPES.filter((_, index) => scopeBits[index]);
  const validityOpts = useMemo(() => { const now = new Date('2026-09-15T08:00:00'); return [{ label: '7 j', days: 7 }, { label: '30 j', days: 30 }, { label: '90 j', days: 90 }, { label: '1 an', days: 365 }].map(option => ({ ...option, expiresAt: new Date(now.getTime() + option.days * 86400000).toISOString().slice(0, 16).replace('T', ' ') })); }, []);
  const chosen = validityOpts[validity]; const canIssue = selectedScopes.length > 0;
  const issueToken = () => { setTouched(true); if (!canIssue) return null; const fake = `${asset?.id || 'asset'}_${Date.now()}_${selectedScopes.length}s`; let hash = 0; for (const character of fake) hash = (hash * 31 + character.charCodeAt(0)) >>> 0; const jti = `jti_${asset?.id || 'x'}_${hash.toString(16).padStart(6, '0')}`; const header = btoa(JSON.stringify({ alg: 'RS256', kid: 'darta-asset-2026', typ: 'JWT' })); const payload = btoa(JSON.stringify({ iss: 'darta.systems.ai/console', sub: asset ? `asset:${asset.id}` : 'user:op', aud: selectedScopes.map(scope => scope.id), iat: Math.round(Date.now() / 1000), exp: Math.round(Date.now() / 1000) + chosen.days * 86400, jti, type: asset ? `asset.${asset.asset_type}.${asset.id}` : 'session.user' })).replace(/=/g, ''); const sig = Array.from({ length: 32 }, (_, index) => ((hash * (index + 7)) >>> 0).toString(16).slice(-1)).join(''); const result: IssuedToken = { jti, kind: asset ? `asset.${asset.asset_type}.${asset.id}` : 'session.user', status: 'active', issuedAt: new Date().toISOString().slice(0, 16).replace('T', ' '), expiresAt: chosen.expiresAt, lastUsed: 'jamais', token: `${header}.${payload}.${sig}` }; setIssuedToken(result); setStep(1); return result; };
  return <Modal open={open} onClose={onClose} size="lg" title={asset ? `Émettre un jeton pour « ${asset.name} »` : 'Émettre un jeton'} confirmLabel={step === 0 ? 'Émettre' : "J'ai sauvegardé"} cancelLabel={step === 0 ? 'Annuler' : undefined} danger={false} onConfirm={() => { if (step === 0) { const token = issueToken(); if (token) onCreate?.(token); } else onClose?.(); }} hideFooter={false}>
    {step === 0 ? <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>{asset && <KVGrid pairs={[['Appareil', asset.name], ['Type', asset.asset_type === 'drone' ? 'Drone' : 'Station sol'], ['Modèle', `${asset.manufacturer} ${asset.model}`], ['Niv. batterie', `${asset.battery} %`]]} />}<Field label="Durée de validité" required help="Une fois expiré, un nouveau jeton devra être émis."><SegmentedControl items={validityOpts.map(option => option.label)} value={validity} onChange={setValidity} /></Field><Field label="Scopes (permissions)" required help={`Sélectionnez au moins un scope. ${selectedScopes.length} sélectionné(s).`}><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 8 }}>{DEFAULT_SCOPES.map((scope, index) => <label key={scope.id} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '8px 10px', border: `1px solid ${scopeBits[index] ? 'var(--brand)' : 'var(--line-2)'}`, background: scopeBits[index] ? 'var(--brand-soft)22' : 'var(--bg-2)', borderRadius: 8, cursor: 'pointer', fontSize: 12.5 }}><input type="checkbox" checked={scopeBits[index]} onChange={() => { const next = [...scopeBits]; next[index] = !next[index]; setScopeBits(next); }} style={{ accentColor: 'var(--brand)' }} /><div><div style={{ fontWeight: 600 }}>{scope.label}</div><div style={{ fontFamily: 'var(--mono)', fontSize: 10.5, color: 'var(--text-3)' }}>{scope.id}</div></div></label>)}</div></Field>{touched && !canIssue && <Alert tone="warn" title="Sélection incomplète">Veuillez sélectionner au moins un scope.</Alert>}<Alert tone="info" icon={<Icon name="shield" size={16} />}>Ce jeton sera signé avec la clé privée du service. Conservez-le dans un endroit sécurisé (il ne sera pas ré-affiché).</Alert></div> : <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}><Alert tone="ok" title="Jeton émis avec succès">Identifiant <code style={{ fontFamily: 'var(--mono)' }}>{issuedToken?.jti}</code>. Expire le {issuedToken?.expiresAt}.</Alert>{issuedToken && <TokenBox token={issuedToken.token} />}</div>}
  </Modal>;
}
