import { useEffect, useState } from 'react';
import { Field, Input, SegmentedControl, Alert } from '@components/ui';
import { Modal } from '@components/feedback';
import { Steps, ZoneCapacity } from '@components/specialized';
import Icon from '@icons';
import type { MissionEditModalProps } from './MissionEditModal.types';

const MISSION_STATUSES = [{ id: 'draft', label: 'Brouillon' }, { id: 'pending', label: 'En attente' }, { id: 'active', label: 'Active' }, { id: 'completed', label: 'Terminée' }, { id: 'archived', label: 'Archivée' }];
export default function MissionEditModal({ open, onClose, initialMission = null, onSave, assets = [], operatorName = '' }: MissionEditModalProps) {
  const isEdit = Boolean(initialMission); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [operator, setOperator] = useState(operatorName || ''); const [statusIdx, setStatusIdx] = useState(0); const [zoneCount, setZoneCount] = useState(0); const [assetCount, setAssetCount] = useState(0); const [touched, setTouched] = useState<Record<string, boolean>>({});
  useEffect(() => { if (!open) return; if (initialMission) { setName(initialMission.name || ''); setDescription(initialMission.description || ''); setOperator(initialMission.operator || operatorName || ''); const statusIndex = Math.max(0, MISSION_STATUSES.findIndex(status => status.id === initialMission.status)); setStatusIdx(statusIndex >= 0 ? statusIndex : 0); setZoneCount(initialMission.zoneCount || 0); setAssetCount(initialMission.assetCount || 0); } else { setName(''); setDescription(''); setOperator(operatorName || ''); setStatusIdx(1); setZoneCount(0); setAssetCount(0); } setTouched({}); }, [open, initialMission, operatorName]);
  const errors: Record<string, string> = {}; if (touched.name && !name.trim()) errors.name = 'Nom de mission requis'; const statusId = MISSION_STATUSES[statusIdx]?.id; const activatingWithoutAssets = statusId === 'active' && assetCount === 0; const isValid = Boolean(name.trim()) && !activatingWithoutAssets; const markTouched = () => setTouched({ name: true }); const capacityMax = 10;
  return <Modal open={open} onClose={onClose} size="lg" title={isEdit ? `Modifier la mission · ${initialMission?.name || ''}` : 'Modifier la mission'} confirmLabel="Enregistrer" danger={false} onConfirm={() => { markTouched(); if (!isValid) return; onSave?.({ id: initialMission?.id || `m_${Date.now().toString(36)}`, name: name.trim(), description: description.trim(), operator: operator.trim(), status: statusId, zoneCount, assetCount, color: initialMission?.color || '#2f8fd0' }); }}>
    <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}><Steps steps={[{ label: 'Contexte' }, { label: 'Zones' }, { label: 'Assets' }, { label: 'Revue' }]} current={isEdit ? 3 : 1} /><Field label="Nom de la mission" required invalid={!!errors.name} help={errors.name}><Input placeholder="ex : Avenue Germaine AHIDJO" value={name} onChange={event => setName(event.target.value)} onBlur={() => setTouched(current => ({ ...current, name: true }))} invalid={!!errors.name} /></Field><Field label="Opérateur responsable"><Input placeholder="Nom de l'opérateur" value={operator} onChange={event => setOperator(event.target.value)} /></Field><Field label="Périmètre / Description" help="Facultatif — résumé opérationnel"><Input as="textarea" rows={3} placeholder="Surveillance de périmètre, itinéraire, consignes…" value={description} onChange={event => setDescription(event.target.value)} /></Field><Field label="Statut"><SegmentedControl items={MISSION_STATUSES.map(status => status.label)} value={statusIdx} onChange={setStatusIdx} /></Field><div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 12 }}><Field label={`Zones associées · ${zoneCount}`} help="Se référencer à l'outil de traçage de polygones"><div style={{ display: 'flex', gap: 6, alignItems: 'center' }}><button type="button" className="btn btn-sm" onClick={() => setZoneCount(value => Math.max(0, value - 1))} style={{ minWidth: 32, justifyContent: 'center' }}>−</button><div style={{ flex: 1, textAlign: 'center', fontWeight: 700, fontFamily: 'var(--mono)' }}>{zoneCount}</div><button type="button" className="btn btn-sm btn-primary" onClick={() => setZoneCount(value => Math.min(capacityMax, value + 1))} style={{ minWidth: 32, justifyContent: 'center' }}>+</button></div></Field><Field label={`Appareils associés · ${assetCount}`} help={assetCount === 0 ? 'Aucun appareil assigné' : undefined}><div style={{ display: 'flex', gap: 6, alignItems: 'center' }}><button type="button" className="btn btn-sm" onClick={() => setAssetCount(value => Math.max(0, value - 1))} style={{ minWidth: 32, justifyContent: 'center' }}>−</button><div style={{ flex: 1, textAlign: 'center', fontWeight: 700, fontFamily: 'var(--mono)' }}>{assetCount}</div><button type="button" className="btn btn-sm btn-primary" onClick={() => setAssetCount(value => Math.min(assets.length || 6, value + 1))} style={{ minWidth: 32, justifyContent: 'center' }}>+</button></div></Field></div><ZoneCapacity used={zoneCount} max={capacityMax} />{activatingWithoutAssets && <Alert tone="warn" title="Statut « Active » invalide">Assignez au moins un appareil avant d'activer la mission, ou choisissez le statut « En attente ».</Alert>}{isEdit && initialMission?.badge && <Alert tone="info" icon={<Icon name="mission" size={16} />}>Code mission : <strong style={{ fontFamily: 'var(--mono)' }}>{initialMission.badge}</strong></Alert>}</div>
  </Modal>;
}
