import { useEffect, useState } from 'react';
import { Field, Input, SegmentedControl, Alert } from '@components/ui';
import { Modal } from '@components/feedback';
import { KVGrid } from '@components/data';
import Icon from '@icons';
import type { AssetFormModalProps } from './AssetFormModal.types';

const ASSET_TYPES = [{ id: 'drone', label: 'Drone', icon: '✈' }, { id: 'monitoring-station', label: 'Station sol', icon: '◆' }, { id: 'camera', label: 'Caméra IP', icon: '◉' }, { id: 'sensor', label: 'Capteur', icon: '◎' }];
export default function AssetFormModal({ open, onClose, initialAsset = null, onSave }: AssetFormModalProps) {
  const isEdit = Boolean(initialAsset); const [name, setName] = useState(''); const [manufacturer, setManufacturer] = useState(''); const [model, setModel] = useState(''); const [assetType, setAssetType] = useState(0); const [serial, setSerial] = useState(''); const [notes, setNotes] = useState(''); const [touched, setTouched] = useState<Record<string, boolean>>({});
  useEffect(() => { if (!open) return; if (initialAsset) { setName(initialAsset.name || ''); setManufacturer(initialAsset.manufacturer || ''); setModel(initialAsset.model || ''); setAssetType(Math.max(0, ASSET_TYPES.findIndex(type => type.id === initialAsset.asset_type))); setSerial(initialAsset.serial || ''); setNotes(initialAsset.notes || ''); } else { setName(''); setManufacturer(''); setModel(''); setAssetType(0); setSerial(''); setNotes(''); } setTouched({}); }, [open, initialAsset]);
  const errors: Record<string, string> = {}; if (touched.name && !name.trim()) errors.name = 'Nom requis'; if (touched.manufacturer && !manufacturer.trim()) errors.manufacturer = 'Fabricant requis'; if (touched.model && !model.trim()) errors.model = 'Modèle requis'; if (touched.serial && serial.trim() && serial.trim().length < 4) errors.serial = 'N° S/N trop court'; const isValid = Boolean(name.trim() && manufacturer.trim() && model.trim()); const markTouched = () => setTouched({ name: true, manufacturer: true, model: true, serial: true });
  return <Modal open={open} onClose={onClose} size="lg" title={isEdit ? `Modifier l'appareil · ${initialAsset?.name || ''}` : 'Enregistrer un appareil'} confirmLabel={isEdit ? 'Enregistrer' : 'Ajouter'} danger={false} onConfirm={() => { markTouched(); if (!isValid) return; const assetTypeStr = ASSET_TYPES[assetType]?.id || 'drone'; onSave?.({ id: initialAsset?.id || `a_${Date.now().toString(36)}`, name: name.trim(), manufacturer: manufacturer.trim(), model: model.trim(), asset_type: assetTypeStr, serial: serial.trim() || undefined, notes: notes.trim() || undefined, battery: initialAsset?.battery ?? 100, last: initialAsset?.last ?? 'à l’instant' }); }}>
    <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}><Field label="Type d'appareil" required><SegmentedControl items={ASSET_TYPES.map(type => `${type.icon} ${type.label}`)} value={assetType} onChange={setAssetType} /></Field><div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 12 }}><Field label="Nom / identifiant" required invalid={!!errors.name} help={errors.name}><Input placeholder="ex : skydroid1" value={name} onChange={event => setName(event.target.value)} onBlur={() => setTouched(current => ({ ...current, name: true }))} invalid={!!errors.name} /></Field><Field label="N° de série / MAC" help="Facultatif — identifiant matériel" invalid={!!errors.serial}><Input placeholder="ex : AA:BB:CC:DD:EE:FF" value={serial} onChange={event => setSerial(event.target.value)} onBlur={() => setTouched(current => ({ ...current, serial: true }))} invalid={!!errors.serial} /></Field><Field label="Fabricant" required invalid={!!errors.manufacturer} help={errors.manufacturer}><Input placeholder="ex : Skydroid" value={manufacturer} onChange={event => setManufacturer(event.target.value)} onBlur={() => setTouched(current => ({ ...current, manufacturer: true }))} invalid={!!errors.manufacturer} /></Field><Field label="Modèle" required invalid={!!errors.model} help={errors.model}><Input placeholder="ex : H16" value={model} onChange={event => setModel(event.target.value)} onBlur={() => setTouched(current => ({ ...current, model: true }))} invalid={!!errors.model} /></Field></div><Field label="Notes internes" help="Facultatif — remarques opérationnelles"><Input as="textarea" rows={3} placeholder="Emplacement géographique, opérateur attitré, intervalle de maintenance…" value={notes} onChange={event => setNotes(event.target.value)} /></Field>{isEdit && initialAsset && <KVGrid pairs={[['ID interne', initialAsset.id], ['Niveau batterie', `${initialAsset.battery} %`], ['Dernière activité', initialAsset.last || '—']]} />}<Alert tone="info" icon={<Icon name="shield" size={16} />}>Une fois enregistré, un jeton d'accès pourra être émis depuis la fiche de l'appareil.</Alert></div>
  </Modal>;
}
